{% set name = "tree_sitter_languages" %}
{% set version = "1.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/grantjenks/py-tree-sitter-languages/archive/refs/tags/v{{ version }}.tar.gz
  sha256: eb3c3f61485837331ea6b45f44ce8a3e985ac127241524fdd08a83b05a366f20

build:
  skip: true  # [py<36]
  script: |
    set -euxo pipefail                                           # [unix]
    alias cc="${CC}"                                             # [unix]
    cc --version                                                 # [unix]
    {{ PYTHON }} build.py
    {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - cython
    - pip
    - python
    - setuptools
    - tree_sitter
  run:
    - python
    - tree_sitter

test:
  imports:
    - tree_sitter_languages
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/grantjenks/py-tree-sitter-languages
  summary: Python Bindings for Tree Sitter with All Languages
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
