{% set name = "tree_sitter_languages" %}
{% set version = "1.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/grantjenks/py-tree-sitter-languages/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5628eb24b845235724200d4ce8c280779380ddff1c9b5e39a0fb09555aaac63c

build:
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - cython
    - pip
    - python
  run:
    - python
    - tree_sitter

test:
  imports:
    - tree_sitter_languages
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/grantjenks/py-tree-sitter-languages
  summary: Python Bindings for Tree Sitter with All Languages
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
