{% set name = "tree_sitter_languages" %}
{% set version = "1.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/grantjenks/py-tree-sitter-languages/archive/refs/tags/v{{ version }}.tar.gz
  sha256: cdd03196ebaf8f486db004acd07a5b39679562894b47af6b20d28e4aed1a6ab5

build:
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - pip
    - python
  run:
    - python
    - tree_sitter

test:
  imports:
    - tree_sitter_languages
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/grantjenks/py-tree-sitter-languages
  summary: Python Bindings for Tree Sitter with All Languages
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
    - davidbrochart
