context:
  name: tree_sitter_languages
  version: 1.10.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/grantjenks/py-tree-sitter-languages/archive/refs/tags/v${{ version }}.tar.gz
  sha256: cdd03196ebaf8f486db004acd07a5b39679562894b47af6b20d28e4aed1a6ab5

build:
  number: 0
  skip: match(python, "<3.6")

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then: cython
    - ${{ compiler('c') }}
    - tree_sitter
    - git
  host:
    - cython
    - pip
    - python
    - tree_sitter
  run:
    - python
    - tree_sitter

tests:
  - python:
      imports:
        - tree_sitter_languages
      pip_check: true
  - script:
      - python -c "from tree_sitter_languages import get_language, get_parser; language = get_language('python'); parser = get_parser('python')"

about:
  summary: Python Bindings for Tree Sitter with All Languages
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/grantjenks/py-tree-sitter-languages

extra:
  recipe-maintainers:
    - thewchan
    - davidbrochart
    - moritzwilksch

